### PR TITLE
197 search and filter function

### LINKED ISSUE #197: search and filter function
### Description
Implement filter and search functions in detail course, download, pin course

### PR DESCRIPTION
**Pull request by Sainaamr**
Title: Implementation of Search and Filter Functionality Across Course Views

Description:
Implemented search and filter features in the Detail Course View, MyCourse, Public Course, and Pinned Course sections. Default filter settings are configured as follows:
- Detail Course View: 'Newest First'
- Other Views (MyCourse, Public Course, Pinned Course): 'Semester', with the current semester as the default.

Note: Encountered an unresolved issue with the search bar color changing on scrolling. Assistance needed to address this bug.

- closes #197

### CODE REVIEW

**Review by GravityDarkLab — CHANGES_REQUESTED** [review]
**Problem**: 
PinnedView` not working.

- **Details**:  
If i pin a course, it don t get displayed in the Pinned View.
If i unpin, it says ressource not found.
if I do the same from the course details view, it works fine.

(p.s Video and screenshots were already communicated with Saina)

**Comment by Sainaamr** [comment]
> **Problem**: PinnedView` not working.
> 
> * **Details**:
>   If i pin a course, it don t get displayed in the Pinned View.
>   If i unpin, it says ressource not found.
>   if I do the same from the course details view, it works fine.
> 
> (p.s Video and screenshots were already communicated with Saina)

the problem was that in refresh the displayed courses were not being set correctly.

**Review by GravityDarkLab — CHANGES_REQUESTED** [review]
Maybe make the All selected per default ? or better the current Semester.
Same goes for Pinned view which i didn t had recorded here.

https://github.com/TUM-Dev/gocast_mobile/assets/101757413/bb323d44-7bda-4afe-a76b-4308cee27368

**Review by Anishyou — CHANGES_REQUESTED** [review]
If a course is pinned, it does not show in pinned courses

https://github.com/TUM-Dev/gocast_mobile/assets/123313052/e710efde-3f8a-4226-b160-af389fe612f0

**Review by Anishyou — CHANGES_REQUESTED** [review]
Also the filter is not being saved. Once I leave the screen, it resets. 

https://github.com/TUM-Dev/gocast_mobile/assets/123313052/684158c5-103f-4341-8dfe-45f4d205f840

**Comment by Anishyou** [comment]
Also in filter for semester, the tick is very vague and misleading 
Simulator Screenshot - iPhone 15 Pro Max - 2024-01-19 at 00 18 33

**Comment by Anishyou** [comment]
Btw Saina great work 👍

**Comment by Sainaamr** [comment]
I changed how i was handling state completely. how if you set the filter in my course or my public course or pinned it stays consistent every where. In video state instead of a list for stream and a list for thumbnail, i made a list of tuple for both and that's how i order it.

**Review by GravityDarkLab — CHANGES_REQUESTED** [review]
- The filter menu is not wide enough.
- No default filter when i go to my courses for the first time -> Set it to the latest semester.
- There seems to be a wrong function call, always retrieving  "Goland: Praktikum"
- In the pinned when I search for something, exit the search field, the Serach filed don t get emptied and i could induce a wrong state when i switch between filters.

**Review by GravityDarkLab — DISMISSED** [review]
Seems good to me.
Maybe add the search and filter for Downloads, but see this with @Anishyou

**Review by GravityDarkLab — DISMISSED** [review]

**Comment by Sainaamr** [comment]
I commented out the AppBar in the base view because this base view is consistently utilized within stateless content views. Integrating an AppBar that includes a search bar into a stateless view is not ideal. This is because, in a stateless view, when you begin typing in the search bar, the input field loses focus after each character is typed, requiring you to click on it again to continue typing. Consequently, it's more practical to place the AppBar within a stateful view, such as a pinned view, rather than in the content view.

**Review by Anishyou — APPROVED** [review]

**Pull request merged**
