### PR TITLE
184 pin course in detail course view

### PR DESCRIPTION
**Pull request by Sainaamr**
We have added a "Pin Button" that allows users to easily pin and unpin courses directly from the Course Detail page.

### CODE REVIEW

**Review by cbetul — DISMISSED** [review]
it works great good job!

**Review by Anishyou — CHANGES_REQUESTED** [review]
Can you use Theme for color?

**Review by cbetul — APPROVED** [review]
it looks ok to me

**Review by Anishyou — APPROVED** [review]
Great wor! Looks good to me:)

**Pull request merged**
