### PR TITLE
102-improve-my-courses-and-public-courses-view-UI

### PR DESCRIPTION
**Pull request by milenark**
### What was done: 
- update live tag
- display tum id instead of slug
- remove blue background
- correct corners
- display most of course title

**Persisting problem**: (yet not a ui issue) live is always false, despite course having live streams

Screenshot 2023-12-26 at 18 44 47
Screenshot 2023-12-26 at 18 25 15

### CODE REVIEW

**Comment by Anishyou** [comment]
Small question- which Github task is this associated with?
if it is linked with https://github.com/TUM-Dev/gocast_mobile/issues/102 Name the branch automatically.

**Review by GravityDarkLab — CHANGES_REQUESTED** [review]
Please see those...
https://ipraktikumws2324.slack.com/archives/C066LLB4P6V/p1703281838709429

https://ipraktikumws2324.slack.com/archives/C066LLB4P6V/p1703283801848999

**Comment by Anishyou** [comment]
You should always put more than one reviewer. So that your PR request can be reviewed quickly

**Comment by milenark** [comment]
> Please see those... https://ipraktikumws2324.slack.com/archives/C066LLB4P6V/p1703281838709429
> 
> https://ipraktikumws2324.slack.com/archives/C066LLB4P6V/p1703283801848999
> 
> Also to get Your PR reviewed you must request review from at least one person or the iPraktikum-group

I did run 'git pull origin dev' and resolved everything - is something still off?

**Comment by Sainaamr** [comment]
did you merge the dev branch into  the branch?

**Comment by Sainaamr** [comment]
Screenshot 2023-12-27 at 16 35 58
Screenshot 2023-12-27 at 16 35 32



when i run the app on an ipad it looks like this.

**Pull request closed without merging**
