### PR TITLE
#102-Improve-My-courses-and-public-courses-view-UI

### PR DESCRIPTION
**Pull request by milenark**
This is a revised and cleaned up merge request of the previous #159 (info and pictures can be found there) 

#### Recap of what was changed: 
- update live tag
- display tum id instead of slug
- remove blue background
- correct corners
- display most of course title

### CODE REVIEW

**Comment by Anishyou** [comment]
Looks good to me. As there are few changes made. Still, some things need to be worked but overall, it's fine for right now.
Also, the name of the branch should match the task.

**Review by Anishyou — APPROVED** [review]

**Review by Anishyou — CHANGES_REQUESTED** [review]
Why is the headline Courses on the homepage?
It was GoCast right? is it a required change?

**Comment by milenark** [comment]
Yes, it was GoCast. 
I just saw that all the other tabs had descriptive titles: the downloads section had the title 'Downloads', the notifications have the title 'Notifications' and the pinned courses too - I thought if only the courses are different it would be maybe a bit weird and we could align them. 
Or shall I change it back/ change all of them to GoCast?

**Comment by Anishyou** [comment]
> Yes, it was GoCast. I just saw that all the other tabs had descriptive titles: the downloads section had the title 'Downloads', the notifications have the title 'Notifications' and the pinned courses too - I thought if only the courses are different it would be maybe a bit weird and we could align them. Or shall I change it back/ change all of them to GoCast?



> Yes, it was GoCast. I just saw that all the other tabs had descriptive titles: the downloads section had the title 'Downloads', the notifications have the title 'Notifications' and the pinned courses too - I thought if only the courses are different it would be maybe a bit weird and we could align them. Or shall I change it back/ change all of them to GoCast?

It also has Live now that does not correspond to courses. It takes directly to videos.
I would suggest gocast is better to be written.

**Comment by Anishyou** [comment]
Also do not forget to update with dev branch

**Review by GravityDarkLab — CHANGES_REQUESTED** [review]
When in Home screen there is this error in the terminal.
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type ParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a IgnorePointer widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  PhysicalModel ← AnimatedPhysicalModel ← Material ← _ScrollNotificationObserverScope ← NotificationListener<ScrollNotification> ← NotificationListener<ScrollMetricsNotification> ← ScrollNotificationObserver ← _ScaffoldScope ← Scaffold ← BaseView ← ⋯
 ```

**Comment by GravityDarkLab** [comment]
I also merged dev into this Branche.

**Comment by milenark** [comment]
> I would suggest gocast is better to be written.

Sounds good, I can quickly change it back

> It also has Live now that does not correspond to courses. It takes directly to videos. 

Yes I already started working on it, just not in this ui brach. I was thinking under livenow we display currently live streams directly that take you to a video player and not the coursedetailview, instead of just live courses (ignore the look, it's not styled and I'm still testing): 
Screenshot 2023-12-29 at 13 57 30

**Comment by GravityDarkLab** [comment]
> > I would suggest gocast is better to be written.
> 
> Sounds good, I can quickly change it back
> 
> > It also has Live now that does not correspond to courses. It takes directly to videos.
> 
> Yes I already started working on it, just not in this ui brach. I was thinking under livenow we display currently live streams directly that take you to a video player and not the coursedetailview, instead of just live courses (ignore the look, it's not styled and I'm still testing): Screenshot 2023-12-29 at 13 57 30

The lists looks much more better :)

**Review by GravityDarkLab — APPROVED** [review]

**Review by Anishyou — APPROVED** [review]

**Pull request merged**
